src/Entity/CustomImage.php
<?php

namespace App\Entity;

use App\Entity\Traits\TimestampableEntity;
use App\Entity\Traits\ToggleableTrait;
use App\Repository\CustomImageRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=CustomImageRepository::class)
 * @UniqueEntity(fields={"uuid"}, message="System error. Please notify administrator.")
 */
class CustomImage
{
    use TimestampableEntity;
    use ToggleableTrait;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="customImages")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fileName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $originalName;

    /**
     * @ORM\Column(type="uuid", unique=true)
     */
    private $uuid;

    public function __construct()
    {
        $this->uuid = Uuid::v4();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    public function setFileName(string $fileName): self
    {
        $this->fileName = $fileName;

        return $this;
    }

    public function getOriginalName(): ?string
    {
        return $this->originalName;
    }

    public function setOriginalName(string $originalName): self
    {
        $this->originalName = $originalName;

        return $this;
    }

    public function getUuid()
    {
        return $this->uuid;
    }

    public function setUuid($uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function getWebPath(): string
    {
        return '/uploads/' . $this->getFileName();
    }
}

src/Entity/Design.php
<?php

namespace App\Entity;

use App\Entity\Traits\TimestampableEntity;
use App\Repository\DesignRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=DesignRepository::class)
 * @UniqueEntity(fields={"uuid"}, message="System error. Please notify administrator.")
 */
class Design
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="designs")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $backgroundColor;

    /**
     * @ORM\Column(type="json")
     */
    private $frontSideJsonData = [];

    /**
     * @ORM\Column(type="json")
     */
    private $backSideJsonData = [];

    /**
     * @ORM\Column(type="uuid", unique=true)
     */
    private $uuid;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    /**
     * @ORM\Column(type="boolean")
     */
    private $hasNames = false;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $namesSide;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $namesHeight;

    /**
     * @ORM\Column(type="string", length=7, nullable=true)
     */
    private $namesColor;

    /**
     * @ORM\Column(type="boolean")
     */
    private $hasNumbers = false;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $numbersSide;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $numbersHeight;

    /**
     * @ORM\Column(type="string", length=7, nullable=true)
     */
    private $numbersColor;

    /**
     * @ORM\Column(type="blob", nullable=true)
     */
    private $frontSideThumbnail;

    /**
     * @ORM\Column(type="blob", nullable=true)
     */
    private $backSideThumbnail;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2, options={"default"=530})
     */
    private $originalWidth;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2, options={"default"=630})
     */
    private $originalHeight;

    public function __construct()
    {
        $this->uuid = Uuid::v4();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->backgroundColor;
    }

    public function setBackgroundColor(?string $backgroundColor): self
    {
        $this->backgroundColor = $backgroundColor;

        return $this;
    }

    public function getFrontSideJsonData(): ?array
    {
        return $this->frontSideJsonData;
    }

    public function setFrontSideJsonData(array $frontSideJsonData): self
    {
        $this->frontSideJsonData = $frontSideJsonData;

        return $this;
    }

    public function getBackSideJsonData(): ?array
    {
        return $this->backSideJsonData;
    }

    public function setBackSideJsonData(array $backSideJsonData): self
    {
        $this->backSideJsonData = $backSideJsonData;

        return $this;
    }

    public function getUuid()
    {
        return $this->uuid;
    }

    public function setUuid($uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getHasNames(): ?bool
    {
        return $this->hasNames;
    }

    public function setHasNames(bool $hasNames): self
    {
        $this->hasNames = $hasNames;

        return $this;
    }

    public function getNamesSide(): ?string
    {
        return $this->namesSide;
    }

    public function setNamesSide(?string $namesSide): self
    {
        $this->namesSide = $namesSide;

        return $this;
    }

    public function getNamesHeight(): ?int
    {
        return $this->namesHeight;
    }

    public function setNamesHeight(?int $namesHeight): self
    {
        $this->namesHeight = $namesHeight;

        return $this;
    }

    public function getNamesColor(): ?string
    {
        return $this->namesColor;
    }

    public function setNamesColor(?string $namesColor): self
    {
        $this->namesColor = $namesColor;

        return $this;
    }

    public function getHasNumbers(): ?bool
    {
        return $this->hasNumbers;
    }

    public function setHasNumbers(bool $hasNumbers): self
    {
        $this->hasNumbers = $hasNumbers;

        return $this;
    }

    public function getNumbersSide(): ?string
    {
        return $this->numbersSide;
    }

    public function setNumbersSide(?string $numbersSide): self
    {
        $this->numbersSide = $numbersSide;

        return $this;
    }

    public function getNumbersHeight(): ?int
    {
        return $this->numbersHeight;
    }

    public function setNumbersHeight(?int $numbersHeight): self
    {
        $this->numbersHeight = $numbersHeight;

        return $this;
    }

    public function getNumbersColor(): ?string
    {
        return $this->numbersColor;
    }

    public function setNumbersColor(?string $numbersColor): self
    {
        $this->numbersColor = $numbersColor;

        return $this;
    }

    public function getFrontSideThumbnail()
    {
        return $this->frontSideThumbnail;
    }

    public function getFrontSideThumbnailContent()
    {
        return $this->getFrontSideThumbnail() ? stream_get_contents($this->getFrontSideThumbnail()) : null;
    }

    public function setFrontSideThumbnail($frontSideThumbnail): self
    {
        $this->frontSideThumbnail = $frontSideThumbnail;

        return $this;
    }

    public function getBackSideThumbnail()
    {
        return $this->backSideThumbnail;
    }

    public function getBackSideThumbnailContent()
    {
        return $this->getBackSideThumbnail() ? stream_get_contents($this->getBackSideThumbnail()) : null;
    }

    public function setBackSideThumbnail($backSideThumbnail): self
    {
        $this->backSideThumbnail = $backSideThumbnail;

        return $this;
    }

    public function getOriginalWidth(): ?string
    {
        return $this->originalWidth;
    }

    public function setOriginalWidth(string $originalWidth): self
    {
        $this->originalWidth = $originalWidth;

        return $this;
    }

    public function getOriginalHeight(): ?string
    {
        return $this->originalHeight;
    }

    public function setOriginalHeight(string $originalHeight): self
    {
        $this->originalHeight = $originalHeight;

        return $this;
    }

    public function __toString()
    {
        return $this->getUuid()->toRfc4122();
    }
}

src/Controller/Admin/UserController.php
<?php

namespace App\Controller\Admin;

use App\Datatables\UserDatatable;
use App\Entity\User;
use App\Form\Admin\UserType;
use Sg\DatatablesBundle\Datatable\DatatableFactory;
use Sg\DatatablesBundle\Response\DatatableResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="admin_user_index", methods={"GET"})
     */
    public function index(Request $request, DatatableFactory $datatableFactory, DatatableResponse $datatableResponse): Response
    {
        $isAjax = $request->isXmlHttpRequest();

        $datatable = $datatableFactory->create(UserDatatable::class);
        $datatable->buildDatatable();

        if ($isAjax) {
            $datatableResponse->setDatatable($datatable);
            $datatableResponse->getDatatableQueryBuilder();

            return $datatableResponse->getResponse();
        }

        return $this->render('admin/user/index.html.twig', array(
            'datatable' => $datatable,
        ));
    }

    /**
     * @Route("/new", name="admin_user_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordHasherInterface $userPasswordHasherInterface): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->get('role')->getData()) {
                $user->setRoles([$form->get('role')->getData()]);
            }

            $user->setPassword(
                $userPasswordHasherInterface->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('admin_user_index');
        }

        return $this->render('admin/user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('admin/user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user, UserPasswordHasherInterface $userPasswordHasherInterface): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->get('role')->getData()) {
                $user->setRoles([$form->get('role')->getData()]);
            }

            if ($form->get('plainPassword')->getData()) {
                $user->setPassword(
                    $userPasswordHasherInterface->hashPassword(
                        $user,
                        $form->get('plainPassword')->getData()
                    )
                );
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_user_index');
        }

        return $this->render('admin/user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_user_delete", methods={"POST"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_user_index');
    }
}

src/Controller/Frontend/UserController.php
<?php

namespace App\Controller\Frontend;

use App\Entity\CustomImage;
use App\Entity\Design;
use App\Entity\User;
use App\Form\ProfileType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    /**
     * @Route("/user/images", name="frontend_user_images")
     * @IsGranted("ROLE_USER")
     */
    public function index(): Response
    {
        $images = $this->getDoctrine()->getRepository(CustomImage::class)->findBy([
            'user' => $this->getUser()
        ], ['updatedAt' => 'DESC']);

        return $this->render('frontend/user/images.html.twig', [
            'images' => $images,
        ]);
    }

    /**
     * @Route("/user/images/{uuid}/delete", name="frontend_user_image_delete")
     * @IsGranted("ROLE_USER")
     */
    public function deleteImage(CustomImage $customImage): Response
    {
        $originalName = $customImage->getOriginalName();
        $fileName = $customImage->getFileName();

        $this->getDoctrine()->getManager()->remove($customImage);
        $this->getDoctrine()->getManager()->flush();

        $filesystem = new Filesystem();
        $filesystem->remove($this->getParameter('kernel.project_dir') .'/public/uploads/' . $fileName);

        $this->addFlash('success', '"' . $originalName . '" have been successfully removed.');

        return $this->redirectToRoute('frontend_user_images');
    }

    /**
     * @Route("/user/designs", name="frontend_user_designs")
     * @IsGranted("ROLE_USER")
     */
    public function designs(): Response
    {
        $designs = $this->getDoctrine()->getRepository(Design::class)->findBy([
            'user' => $this->getUser()
        ], ['updatedAt' => 'DESC']);

        return $this->render('frontend/user/designs.html.twig', [
            'designs' => $designs,
        ]);
    }

    /**
     * @Route("/user/profile", name="frontend_user_profile")
     * @IsGranted("ROLE_USER")
     */
    public function profile(Request $request, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        $user = $this->getDoctrine()->getRepository(User::class)->find($this->getUser()->getId());

        if (!$user) {
            throw $this->createNotFoundException();
        }

        $form = $this->createForm(ProfileType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->get('plainPassword')->getData() !== null) {
                $user->setPassword(
                    $userPasswordHasher->hashPassword(
                        $user,
                        $form->get('plainPassword')->getData()
                    )
                );
            }

            $this->getDoctrine()->getManager()->persist($user);
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'Profile successfully updated!');
        } elseif ($form->isSubmitted() && !$form->isValid()) {
            $this->addFlash('danger', 'Error saving your profile!');
        }

        return $this->render('frontend/user/profile.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/frontend/user/designs.html.twig
{% extends 'base.html.twig' %}

{% block page_title %}
    My Designs
{% endblock %}

{% block content %}
    <h1 class="display-1 text-secondary text-center">
        {{ block('page_title') }}
    </h1>

    {% embed 'flash.html.twig' %}{% endembed %}

    <div class="callout callout-primary mb-4">Manage and review all designs you have saved previously.</div>

    {% if designs|length == 0 %}
        <div class="callout callout-warning">No designs have been saved. Go to <a href="{{ url('frontend_index') }}" class="text-primary">Design Your Own</a> page and save your design from the preview tab.</div>
    {% endif %}

    <div class="row">
        {% for design in designs %}
            <div class="col col-md-4 col-xl-3">
                <div class="card mb-4">
                    {% set thumbnail = design.frontSideThumbnailContent %}
                    {% set thumbnail_back = design.backSideThumbnailContent %}
                    {% if thumbnail is not null or thumbnail_back is not null %}
                    <img id="thumbnail-{{ design.uuid }}" class="card-img-top card-thumbnail" src="{{ thumbnail is not null ? thumbnail : thumbnail_back }}" alt="{{ design.uuid }}">
                        {% if thumbnail is not null and thumbnail_back is not null %}
                        <div class="card-img-overlay text-primary text-right p-2">
                            <button type="button" class="btn btn-primary icon-btn rounded-pill flip-preview" data-current-side="{{ thumbnail is not null ? 'front' : 'back' }}" data-front-src="{{ thumbnail }}" data-back-src="{{ thumbnail_back }}" data-uuid="{{ design.uuid }}"><i class="fad fa-repeat-alt"></i></button>
                        </div>
                        {% endif %}
                    {% else %}
                        <div class="card-header">
                            No preview available
                        </div>
                    {% endif %}
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div class="text-muted">Created</div>
                            <div>{{ design.createdAt|date('Y-m-d h:i A') }}</div>
                        </li>
                    </ul>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div class="text-muted">Last Updated</div>
                            <div>{{ design.updatedAt|date('Y-m-d h:i A') }}</div>
                        </li>
                    </ul>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{{ url('frontend_load_design', {'uuid': design.uuid}) }}" class="btn btn-primary btn-block"><i class="fad fa-edit"></i>&nbsp;&nbsp;View/Edit</a>
                        </li>
                    </ul>
                </div>

            </div>
        {% endfor %}
    </div>

{% endblock %}

{% block page_js %}
    <script>
        $(document).ready(function () {
            $('.flip-preview').on('click', function () {
                var $thumbnail = $('#thumbnail-' + $(this).data('uuid'));

                if ($(this).data('current-side') === 'front') {
                    $thumbnail.attr('src', $(this).data('back-src'));
                    $(this).data('current-side', 'back');
                } else {
                    $thumbnail.attr('src', $(this).data('front-src'));
                    $(this).data('current-side', 'front');
                }
            });
        });
    </script>
{% endblock %}

templates/frontend/user/images.html.twig
{% extends 'base.html.twig' %}

{% block page_title %}
    My Custom Images
{% endblock %}

{% block content %}
    <h1 class="display-1 text-secondary text-center">
        {{ block('page_title') }}
    </h1>

    {% embed 'flash.html.twig' %}{% endembed %}

    <div class="callout callout-primary mb-4">Manage and review all custom images you have uploaded for the editor.</div>

    {% if images|length == 0 %}
        <div class="callout callout-warning">No image have been uploaded. Go to <a href="{{ url('frontend_index') }}" class="text-primary">Design Your Own</a> page and upload custom images using the upload menu.</div>
    {% endif %}

    <div class="row">
        {% for image in images %}
        <div class="col col-md-4 col-xl-3">
            <div class="card mb-4">
                <img class="card-img-top" src="{{ image.webPath|imagine_filter('image_list') }}" alt="{{ image.originalName }}">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div class="text-muted">File Name</div>
                        <div>{{ image.originalName }}</div>
                    </li>
                </ul>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div class="text-muted">Date Uploaded</div>
                        <div>{{ image.createdAt|date('Y-m-d h:i A') }}</div>
                    </li>
                </ul>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="{{ url('frontend_user_image_delete', {'uuid': image.uuid}) }}" class="btn btn-danger btn-block"><i class="fad fa-trash"></i>&nbsp;&nbsp;Remove</a>
                    </li>
                </ul>
            </div>

        </div>
        {% endfor %}
    </div>

{% endblock %}

templates/frontend/user/profile.html.twig
{% extends 'base.html.twig' %}

{% block page_title %}
    My Profile
{% endblock %}

{% block content %}
    <h1 class="display-1 text-secondary text-center">
        {{ block('page_title') }}
    </h1>

    {% embed 'flash.html.twig' %}{% endembed %}

    <div class="callout callout-primary mb-4">View and update your profile.</div>

    {{ form(form) }}

{% endblock %}